version: 2.1

jobs:
  build_backend:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Create and activate virtual environment
          command: |
            python -m venv venv
            source venv/bin/activate
      - run:
          name: Upgrade pip
          command: |
            source venv/bin/activate  # Ensure the virtual environment is activated
            python -m pip install --upgrade pip
      - run:
          name: Install Python dependencies
          command: |
            cd backend/app
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Check installed packages
          command: |
            source venv/bin/activate
            pip list
      - run:
          name: Run Python tests
          command: |
            source venv/bin/activate
            pytest

  build_frontend:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Node.js dependencies
          command: npm install
      - run:
          name: Build React app
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy Backend and Frontend
          command: |
            . venv/bin/activate
            # Your backend deploy commands here, e.g.:
            # scp -r /workspace/* user@server:/path/to/deploy/
            # Deploy React build files (example):
            scp -r /workspace/build/* user@server:/var/www/html/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_backend
      - build_frontend:
          requires:
            - build_backend
      - deploy:
          requires:
            - build_frontend
