import React, { useState, useEffect, useCallback } from "react";
import axios from "axios";
import CircularProgress from "@mui/material/CircularProgress";
import SendIcon from "@mui/icons-material/Send"; // arrow icon
import SpinningLogo from "./SpinningLogo";
import Spinning_Ai_Logo from "./Spinning_Ai_Logo";

import {
  Container,
  Grid2 as Grid,
  Typography,
  CssBaseline,
  Paper,
  Box,
  Checkbox,
  FormControl,
  InputLabel,
  MenuItem,
  Select,
  SelectChangeEvent,
  TextField,
  Button,
  IconButton,
} from "@mui/material";

function DalleImageGenerator(props) {
  const { endpoint } = props;
  const [prompt, setPrompt] = useState("");
  const [imageUrl, setImageUrl] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");

  // Function to parse error message
  const parseErrorMessage = (errorString) => {
    try {
      let jsonString = errorString.replace(/^Error code: \d+ - /, "");
      jsonString = jsonString
        .replace(/'/g, '"') // Replace single quotes with double quotes
        .replace(/None/g, "null"); // Replace None with null
      const errorObj = JSON.parse(jsonString);
      return errorObj.error.message;
    } catch (e) {
      return "An unexpected error occurred";
    }
  };

  const fetchData = useCallback(async () => {
    setIsLoading(true);
    setError("");
    setImageUrl("");
    try {
      const response = await axios.post(endpoint, {
        prompt: prompt,
      });

      setImageUrl(response.data.imageUrl);
    } catch (error) {
      //setError(parseErrorMessage(error.response.data?.error));
      //setError(error.response.data.error);
      setError(error.response.data);
    } finally {
      setIsLoading(false);
    }
  }, [endpoint, prompt]);

  const fetchData_test = useCallback(async () => {
    setIsLoading(false);
    console.info("Testing");
  }, [endpoint]);

  useEffect(() => {
    setIsLoading(true);
    fetchData();
  }, [endpoint]);

  return (
    //<Container sx={{ mt: "1px", width: "100%" }}>
    <Container maxWidth="md">
      <h2 className="text-info text-center">Generate an AI Image</h2>
      {isLoading ? (
        <div className="loader-container">
          <CircularProgress size={120} />
        </div>
      ) : (
        <Box
          component="form"
          sx={{
            "& .MuiTextField-root": {
              m: 2,
            },
          }}
          noValidate
          autoComplete="off"
        >
          <Box
            sx={{
              display: "flex",
              alignItems: "center",
            }}
          >
            <Spinning_Ai_Logo />
            <TextField
              fullWidth
              multiline
              id="outlined-multiline-flexible"
              label="Describe what image you want to create"
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              sx={{
                mt: 2,
                "& .MuiOutlinedInput-root": {
                  borderRadius: "20px", // round the input box
                },
              }}
            />

            <IconButton
              type="submit"
              sx={{
                ml: 1,
                bgcolor: "Highlight", // ChatGPT green
                color: "white",
                "&:hover": { bgcolor: "#0d8c6c" },
                display: "flex",
                justifyContent: "flex-end",
              }}
              onClick={fetchData}
              disabled={isLoading}
            >
              <SendIcon />
            </IconButton>
          </Box>

          <Box
            sx={{
              display: "flex",
              justifyContent: "center", // Horizontal centering
              alignItems: "center", // Vertical centering
              minHeight: "200px", // Optional: Set a height to see vertical centering
              width: "100%", // Optional: Full width or set a specific width like '500px'
              mt: 10,
            }}
          >
            {error ? (
              <Typography color="error" variant="body1" sx={{ fontSize: 30 }}>
                {error}
              </Typography>
            ) : (
              imageUrl && (
                <img
                  src={imageUrl}
                  alt="Generated by DALL·E-3"
                  title={prompt}
                />
              )
            )}
          </Box>
        </Box>
      )}
    </Container>
  );
}

export default DalleImageGenerator;
